// schema.proto
syntax = "proto3";
package book_requests;
option go_package = "./protoBookRequests";

message BookDeviceInfo {
  string secret = 1;
  string appVer = 2;
  int32 deviceType = 3;
  string osVer = 4;
  bool isTablet = 5;
  int32 imageQuality = 6;
}

message BookUserPoint {
  uint32 free = 1;
  uint32 paid = 2;
}

message BookWebMangaViewerRequest {
  BookDeviceInfo deviceInfo = 1;
  uint32 chapterId = 2;       // Received value: 24683
  bool useTicket = 3;         // Received value: false (0)
  uint32 consumePoint = 4;    // Received value: 0
}

message BookImage {
  string imageUrl = 1;
  string urlScheme = 2;
  string iv = 3;
  string encryptionKey = 4;
  uint32 imageWidth = 5;
  uint32 imageHeight = 6;
}

message ViewerPage {
  BookImage image = 1;
}

message WebInfo {
  uint32 id = 1; 
  string title = 2;
  string cover_url = 3;
  uint32 price = 4;
  uint32 discount_price = 5;
  bool is_purchased = 6;
  bool is_free = 7;
  uint32 display_order = 8;
  string release_date = 10;
  string sample_image_url = 13;
  string campaign_text = 14;
  string description = 15;
  string series_title = 20;
}

message WebMangaViewerResponse {
  repeated ViewerPage pages = 1;
  WebInfo info = 8;
}