// schema.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: schemaBook.proto

package protoBookRequests

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookDeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	AppVer        string                 `protobuf:"bytes,2,opt,name=appVer,proto3" json:"appVer,omitempty"`
	DeviceType    int32                  `protobuf:"varint,3,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	OsVer         string                 `protobuf:"bytes,4,opt,name=osVer,proto3" json:"osVer,omitempty"`
	IsTablet      bool                   `protobuf:"varint,5,opt,name=isTablet,proto3" json:"isTablet,omitempty"`
	ImageQuality  int32                  `protobuf:"varint,6,opt,name=imageQuality,proto3" json:"imageQuality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookDeviceInfo) Reset() {
	*x = BookDeviceInfo{}
	mi := &file_schemaBook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookDeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookDeviceInfo) ProtoMessage() {}

func (x *BookDeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_schemaBook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookDeviceInfo.ProtoReflect.Descriptor instead.
func (*BookDeviceInfo) Descriptor() ([]byte, []int) {
	return file_schemaBook_proto_rawDescGZIP(), []int{0}
}

func (x *BookDeviceInfo) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *BookDeviceInfo) GetAppVer() string {
	if x != nil {
		return x.AppVer
	}
	return ""
}

func (x *BookDeviceInfo) GetDeviceType() int32 {
	if x != nil {
		return x.DeviceType
	}
	return 0
}

func (x *BookDeviceInfo) GetOsVer() string {
	if x != nil {
		return x.OsVer
	}
	return ""
}

func (x *BookDeviceInfo) GetIsTablet() bool {
	if x != nil {
		return x.IsTablet
	}
	return false
}

func (x *BookDeviceInfo) GetImageQuality() int32 {
	if x != nil {
		return x.ImageQuality
	}
	return 0
}

type BookUserPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Free          uint32                 `protobuf:"varint,1,opt,name=free,proto3" json:"free,omitempty"`
	Paid          uint32                 `protobuf:"varint,2,opt,name=paid,proto3" json:"paid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookUserPoint) Reset() {
	*x = BookUserPoint{}
	mi := &file_schemaBook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookUserPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookUserPoint) ProtoMessage() {}

func (x *BookUserPoint) ProtoReflect() protoreflect.Message {
	mi := &file_schemaBook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookUserPoint.ProtoReflect.Descriptor instead.
func (*BookUserPoint) Descriptor() ([]byte, []int) {
	return file_schemaBook_proto_rawDescGZIP(), []int{1}
}

func (x *BookUserPoint) GetFree() uint32 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *BookUserPoint) GetPaid() uint32 {
	if x != nil {
		return x.Paid
	}
	return 0
}

type BookWebMangaViewerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceInfo    *BookDeviceInfo        `protobuf:"bytes,1,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
	ChapterId     uint32                 `protobuf:"varint,2,opt,name=chapterId,proto3" json:"chapterId,omitempty"`       // Received value: 24683
	UseTicket     bool                   `protobuf:"varint,3,opt,name=useTicket,proto3" json:"useTicket,omitempty"`       // Received value: false (0)
	ConsumePoint  uint32                 `protobuf:"varint,4,opt,name=consumePoint,proto3" json:"consumePoint,omitempty"` // Received value: 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookWebMangaViewerRequest) Reset() {
	*x = BookWebMangaViewerRequest{}
	mi := &file_schemaBook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookWebMangaViewerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookWebMangaViewerRequest) ProtoMessage() {}

func (x *BookWebMangaViewerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schemaBook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookWebMangaViewerRequest.ProtoReflect.Descriptor instead.
func (*BookWebMangaViewerRequest) Descriptor() ([]byte, []int) {
	return file_schemaBook_proto_rawDescGZIP(), []int{2}
}

func (x *BookWebMangaViewerRequest) GetDeviceInfo() *BookDeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *BookWebMangaViewerRequest) GetChapterId() uint32 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *BookWebMangaViewerRequest) GetUseTicket() bool {
	if x != nil {
		return x.UseTicket
	}
	return false
}

func (x *BookWebMangaViewerRequest) GetConsumePoint() uint32 {
	if x != nil {
		return x.ConsumePoint
	}
	return 0
}

type BookImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	UrlScheme     string                 `protobuf:"bytes,2,opt,name=urlScheme,proto3" json:"urlScheme,omitempty"`
	Iv            string                 `protobuf:"bytes,3,opt,name=iv,proto3" json:"iv,omitempty"`
	EncryptionKey string                 `protobuf:"bytes,4,opt,name=encryptionKey,proto3" json:"encryptionKey,omitempty"`
	ImageWidth    uint32                 `protobuf:"varint,5,opt,name=imageWidth,proto3" json:"imageWidth,omitempty"`
	ImageHeight   uint32                 `protobuf:"varint,6,opt,name=imageHeight,proto3" json:"imageHeight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookImage) Reset() {
	*x = BookImage{}
	mi := &file_schemaBook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookImage) ProtoMessage() {}

func (x *BookImage) ProtoReflect() protoreflect.Message {
	mi := &file_schemaBook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookImage.ProtoReflect.Descriptor instead.
func (*BookImage) Descriptor() ([]byte, []int) {
	return file_schemaBook_proto_rawDescGZIP(), []int{3}
}

func (x *BookImage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *BookImage) GetUrlScheme() string {
	if x != nil {
		return x.UrlScheme
	}
	return ""
}

func (x *BookImage) GetIv() string {
	if x != nil {
		return x.Iv
	}
	return ""
}

func (x *BookImage) GetEncryptionKey() string {
	if x != nil {
		return x.EncryptionKey
	}
	return ""
}

func (x *BookImage) GetImageWidth() uint32 {
	if x != nil {
		return x.ImageWidth
	}
	return 0
}

func (x *BookImage) GetImageHeight() uint32 {
	if x != nil {
		return x.ImageHeight
	}
	return 0
}

type ViewerPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *BookImage             `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewerPage) Reset() {
	*x = ViewerPage{}
	mi := &file_schemaBook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewerPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewerPage) ProtoMessage() {}

func (x *ViewerPage) ProtoReflect() protoreflect.Message {
	mi := &file_schemaBook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewerPage.ProtoReflect.Descriptor instead.
func (*ViewerPage) Descriptor() ([]byte, []int) {
	return file_schemaBook_proto_rawDescGZIP(), []int{4}
}

func (x *ViewerPage) GetImage() *BookImage {
	if x != nil {
		return x.Image
	}
	return nil
}

type WebInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CoverUrl       string                 `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Price          uint32                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	DiscountPrice  uint32                 `protobuf:"varint,5,opt,name=discount_price,json=discountPrice,proto3" json:"discount_price,omitempty"`
	IsPurchased    bool                   `protobuf:"varint,6,opt,name=is_purchased,json=isPurchased,proto3" json:"is_purchased,omitempty"`
	IsFree         bool                   `protobuf:"varint,7,opt,name=is_free,json=isFree,proto3" json:"is_free,omitempty"`
	DisplayOrder   uint32                 `protobuf:"varint,8,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	ReleaseDate    string                 `protobuf:"bytes,10,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	SampleImageUrl string                 `protobuf:"bytes,13,opt,name=sample_image_url,json=sampleImageUrl,proto3" json:"sample_image_url,omitempty"`
	CampaignText   string                 `protobuf:"bytes,14,opt,name=campaign_text,json=campaignText,proto3" json:"campaign_text,omitempty"`
	Description    string                 `protobuf:"bytes,15,opt,name=description,proto3" json:"description,omitempty"`
	SeriesTitle    string                 `protobuf:"bytes,20,opt,name=series_title,json=seriesTitle,proto3" json:"series_title,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WebInfo) Reset() {
	*x = WebInfo{}
	mi := &file_schemaBook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebInfo) ProtoMessage() {}

func (x *WebInfo) ProtoReflect() protoreflect.Message {
	mi := &file_schemaBook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebInfo.ProtoReflect.Descriptor instead.
func (*WebInfo) Descriptor() ([]byte, []int) {
	return file_schemaBook_proto_rawDescGZIP(), []int{5}
}

func (x *WebInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WebInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WebInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *WebInfo) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *WebInfo) GetDiscountPrice() uint32 {
	if x != nil {
		return x.DiscountPrice
	}
	return 0
}

func (x *WebInfo) GetIsPurchased() bool {
	if x != nil {
		return x.IsPurchased
	}
	return false
}

func (x *WebInfo) GetIsFree() bool {
	if x != nil {
		return x.IsFree
	}
	return false
}

func (x *WebInfo) GetDisplayOrder() uint32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *WebInfo) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *WebInfo) GetSampleImageUrl() string {
	if x != nil {
		return x.SampleImageUrl
	}
	return ""
}

func (x *WebInfo) GetCampaignText() string {
	if x != nil {
		return x.CampaignText
	}
	return ""
}

func (x *WebInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WebInfo) GetSeriesTitle() string {
	if x != nil {
		return x.SeriesTitle
	}
	return ""
}

type WebMangaViewerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         []*ViewerPage          `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	Info          *WebInfo               `protobuf:"bytes,8,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebMangaViewerResponse) Reset() {
	*x = WebMangaViewerResponse{}
	mi := &file_schemaBook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebMangaViewerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebMangaViewerResponse) ProtoMessage() {}

func (x *WebMangaViewerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schemaBook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebMangaViewerResponse.ProtoReflect.Descriptor instead.
func (*WebMangaViewerResponse) Descriptor() ([]byte, []int) {
	return file_schemaBook_proto_rawDescGZIP(), []int{6}
}

func (x *WebMangaViewerResponse) GetPages() []*ViewerPage {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *WebMangaViewerResponse) GetInfo() *WebInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_schemaBook_proto protoreflect.FileDescriptor

const file_schemaBook_proto_rawDesc = "" +
	"\n" +
	"\x10schemaBook.proto\x12\rbook_requests\"\xb6\x01\n" +
	"\x0eBookDeviceInfo\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x16\n" +
	"\x06appVer\x18\x02 \x01(\tR\x06appVer\x12\x1e\n" +
	"\n" +
	"deviceType\x18\x03 \x01(\x05R\n" +
	"deviceType\x12\x14\n" +
	"\x05osVer\x18\x04 \x01(\tR\x05osVer\x12\x1a\n" +
	"\bisTablet\x18\x05 \x01(\bR\bisTablet\x12\"\n" +
	"\fimageQuality\x18\x06 \x01(\x05R\fimageQuality\"7\n" +
	"\rBookUserPoint\x12\x12\n" +
	"\x04free\x18\x01 \x01(\rR\x04free\x12\x12\n" +
	"\x04paid\x18\x02 \x01(\rR\x04paid\"\xba\x01\n" +
	"\x19BookWebMangaViewerRequest\x12=\n" +
	"\n" +
	"deviceInfo\x18\x01 \x01(\v2\x1d.book_requests.BookDeviceInfoR\n" +
	"deviceInfo\x12\x1c\n" +
	"\tchapterId\x18\x02 \x01(\rR\tchapterId\x12\x1c\n" +
	"\tuseTicket\x18\x03 \x01(\bR\tuseTicket\x12\"\n" +
	"\fconsumePoint\x18\x04 \x01(\rR\fconsumePoint\"\xbd\x01\n" +
	"\tBookImage\x12\x1a\n" +
	"\bimageUrl\x18\x01 \x01(\tR\bimageUrl\x12\x1c\n" +
	"\turlScheme\x18\x02 \x01(\tR\turlScheme\x12\x0e\n" +
	"\x02iv\x18\x03 \x01(\tR\x02iv\x12$\n" +
	"\rencryptionKey\x18\x04 \x01(\tR\rencryptionKey\x12\x1e\n" +
	"\n" +
	"imageWidth\x18\x05 \x01(\rR\n" +
	"imageWidth\x12 \n" +
	"\vimageHeight\x18\x06 \x01(\rR\vimageHeight\"<\n" +
	"\n" +
	"ViewerPage\x12.\n" +
	"\x05image\x18\x01 \x01(\v2\x18.book_requests.BookImageR\x05image\"\xa1\x03\n" +
	"\aWebInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tcover_url\x18\x03 \x01(\tR\bcoverUrl\x12\x14\n" +
	"\x05price\x18\x04 \x01(\rR\x05price\x12%\n" +
	"\x0ediscount_price\x18\x05 \x01(\rR\rdiscountPrice\x12!\n" +
	"\fis_purchased\x18\x06 \x01(\bR\visPurchased\x12\x17\n" +
	"\ais_free\x18\a \x01(\bR\x06isFree\x12#\n" +
	"\rdisplay_order\x18\b \x01(\rR\fdisplayOrder\x12!\n" +
	"\frelease_date\x18\n" +
	" \x01(\tR\vreleaseDate\x12(\n" +
	"\x10sample_image_url\x18\r \x01(\tR\x0esampleImageUrl\x12#\n" +
	"\rcampaign_text\x18\x0e \x01(\tR\fcampaignText\x12 \n" +
	"\vdescription\x18\x0f \x01(\tR\vdescription\x12!\n" +
	"\fseries_title\x18\x14 \x01(\tR\vseriesTitle\"u\n" +
	"\x16WebMangaViewerResponse\x12/\n" +
	"\x05pages\x18\x01 \x03(\v2\x19.book_requests.ViewerPageR\x05pages\x12*\n" +
	"\x04info\x18\b \x01(\v2\x16.book_requests.WebInfoR\x04infoB\x15Z\x13./protoBookRequestsb\x06proto3"

var (
	file_schemaBook_proto_rawDescOnce sync.Once
	file_schemaBook_proto_rawDescData []byte
)

func file_schemaBook_proto_rawDescGZIP() []byte {
	file_schemaBook_proto_rawDescOnce.Do(func() {
		file_schemaBook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemaBook_proto_rawDesc), len(file_schemaBook_proto_rawDesc)))
	})
	return file_schemaBook_proto_rawDescData
}

var file_schemaBook_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_schemaBook_proto_goTypes = []any{
	(*BookDeviceInfo)(nil),            // 0: book_requests.BookDeviceInfo
	(*BookUserPoint)(nil),             // 1: book_requests.BookUserPoint
	(*BookWebMangaViewerRequest)(nil), // 2: book_requests.BookWebMangaViewerRequest
	(*BookImage)(nil),                 // 3: book_requests.BookImage
	(*ViewerPage)(nil),                // 4: book_requests.ViewerPage
	(*WebInfo)(nil),                   // 5: book_requests.WebInfo
	(*WebMangaViewerResponse)(nil),    // 6: book_requests.WebMangaViewerResponse
}
var file_schemaBook_proto_depIdxs = []int32{
	0, // 0: book_requests.BookWebMangaViewerRequest.deviceInfo:type_name -> book_requests.BookDeviceInfo
	3, // 1: book_requests.ViewerPage.image:type_name -> book_requests.BookImage
	4, // 2: book_requests.WebMangaViewerResponse.pages:type_name -> book_requests.ViewerPage
	5, // 3: book_requests.WebMangaViewerResponse.info:type_name -> book_requests.WebInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_schemaBook_proto_init() }
func file_schemaBook_proto_init() {
	if File_schemaBook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemaBook_proto_rawDesc), len(file_schemaBook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schemaBook_proto_goTypes,
		DependencyIndexes: file_schemaBook_proto_depIdxs,
		MessageInfos:      file_schemaBook_proto_msgTypes,
	}.Build()
	File_schemaBook_proto = out.File
	file_schemaBook_proto_goTypes = nil
	file_schemaBook_proto_depIdxs = nil
}
