// schema.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: schema.proto

package utils

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	AppVer        string                 `protobuf:"bytes,2,opt,name=appVer,proto3" json:"appVer,omitempty"`
	DeviceType    int32                  `protobuf:"varint,3,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	OsVer         string                 `protobuf:"bytes,4,opt,name=osVer,proto3" json:"osVer,omitempty"`
	IsTablet      bool                   `protobuf:"varint,5,opt,name=isTablet,proto3" json:"isTablet,omitempty"`
	ImageQuality  int32                  `protobuf:"varint,6,opt,name=imageQuality,proto3" json:"imageQuality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceInfo) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *DeviceInfo) GetAppVer() string {
	if x != nil {
		return x.AppVer
	}
	return ""
}

func (x *DeviceInfo) GetDeviceType() int32 {
	if x != nil {
		return x.DeviceType
	}
	return 0
}

func (x *DeviceInfo) GetOsVer() string {
	if x != nil {
		return x.OsVer
	}
	return ""
}

func (x *DeviceInfo) GetIsTablet() bool {
	if x != nil {
		return x.IsTablet
	}
	return false
}

func (x *DeviceInfo) GetImageQuality() int32 {
	if x != nil {
		return x.ImageQuality
	}
	return 0
}

type UserPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Free          uint32                 `protobuf:"varint,1,opt,name=free,proto3" json:"free,omitempty"`
	Paid          uint32                 `protobuf:"varint,2,opt,name=paid,proto3" json:"paid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPoint) Reset() {
	*x = UserPoint{}
	mi := &file_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPoint) ProtoMessage() {}

func (x *UserPoint) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPoint.ProtoReflect.Descriptor instead.
func (*UserPoint) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{1}
}

func (x *UserPoint) GetFree() uint32 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *UserPoint) GetPaid() uint32 {
	if x != nil {
		return x.Paid
	}
	return 0
}

type WebMangaViewerRequest struct {
	state           protoimpl.MessageState                 `protogen:"open.v1"`
	DeviceInfo      *DeviceInfo                            `protobuf:"bytes,1,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
	UseTicket       bool                                   `protobuf:"varint,2,opt,name=useTicket,proto3" json:"useTicket,omitempty"`
	ConsumePoint    *UserPoint                             `protobuf:"bytes,3,opt,name=consumePoint,proto3" json:"consumePoint,omitempty"`
	ChapterId       uint32                                 `protobuf:"varint,4,opt,name=chapterId,proto3" json:"chapterId,omitempty"`
	ChapterArgument *WebMangaViewerRequest_ChapterArgument `protobuf:"bytes,5,opt,name=chapterArgument,proto3" json:"chapterArgument,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WebMangaViewerRequest) Reset() {
	*x = WebMangaViewerRequest{}
	mi := &file_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebMangaViewerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebMangaViewerRequest) ProtoMessage() {}

func (x *WebMangaViewerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebMangaViewerRequest.ProtoReflect.Descriptor instead.
func (*WebMangaViewerRequest) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{2}
}

func (x *WebMangaViewerRequest) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *WebMangaViewerRequest) GetUseTicket() bool {
	if x != nil {
		return x.UseTicket
	}
	return false
}

func (x *WebMangaViewerRequest) GetConsumePoint() *UserPoint {
	if x != nil {
		return x.ConsumePoint
	}
	return nil
}

func (x *WebMangaViewerRequest) GetChapterId() uint32 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *WebMangaViewerRequest) GetChapterArgument() *WebMangaViewerRequest_ChapterArgument {
	if x != nil {
		return x.ChapterArgument
	}
	return nil
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	UrlScheme     string                 `protobuf:"bytes,2,opt,name=urlScheme,proto3" json:"urlScheme,omitempty"`
	Iv            string                 `protobuf:"bytes,3,opt,name=iv,proto3" json:"iv,omitempty"`
	EncryptionKey string                 `protobuf:"bytes,4,opt,name=encryptionKey,proto3" json:"encryptionKey,omitempty"`
	ImageWidth    uint32                 `protobuf:"varint,5,opt,name=imageWidth,proto3" json:"imageWidth,omitempty"`
	ImageHeight   uint32                 `protobuf:"varint,6,opt,name=imageHeight,proto3" json:"imageHeight,omitempty"`
	IsExtraPage   bool                   `protobuf:"varint,7,opt,name=isExtraPage,proto3" json:"isExtraPage,omitempty"`
	ExtraId       uint32                 `protobuf:"varint,8,opt,name=extraId,proto3" json:"extraId,omitempty"`
	ExtraIndex    uint32                 `protobuf:"varint,9,opt,name=extraIndex,proto3" json:"extraIndex,omitempty"`
	ExtraSlotId   uint32                 `protobuf:"varint,10,opt,name=extraSlotId,proto3" json:"extraSlotId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{3}
}

func (x *Image) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Image) GetUrlScheme() string {
	if x != nil {
		return x.UrlScheme
	}
	return ""
}

func (x *Image) GetIv() string {
	if x != nil {
		return x.Iv
	}
	return ""
}

func (x *Image) GetEncryptionKey() string {
	if x != nil {
		return x.EncryptionKey
	}
	return ""
}

func (x *Image) GetImageWidth() uint32 {
	if x != nil {
		return x.ImageWidth
	}
	return 0
}

func (x *Image) GetImageHeight() uint32 {
	if x != nil {
		return x.ImageHeight
	}
	return 0
}

func (x *Image) GetIsExtraPage() bool {
	if x != nil {
		return x.IsExtraPage
	}
	return false
}

func (x *Image) GetExtraId() uint32 {
	if x != nil {
		return x.ExtraId
	}
	return 0
}

func (x *Image) GetExtraIndex() uint32 {
	if x != nil {
		return x.ExtraIndex
	}
	return 0
}

func (x *Image) GetExtraSlotId() uint32 {
	if x != nil {
		return x.ExtraSlotId
	}
	return 0
}

type WebView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebView) Reset() {
	*x = WebView{}
	mi := &file_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebView) ProtoMessage() {}

func (x *WebView) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebView.ProtoReflect.Descriptor instead.
func (*WebView) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{4}
}

func (x *WebView) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type LastPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastPage) Reset() {
	*x = LastPage{}
	mi := &file_schema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastPage) ProtoMessage() {}

func (x *LastPage) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastPage.ProtoReflect.Descriptor instead.
func (*LastPage) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{5}
}

type GoogleAds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleAds) Reset() {
	*x = GoogleAds{}
	mi := &file_schema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleAds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleAds) ProtoMessage() {}

func (x *GoogleAds) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleAds.ProtoReflect.Descriptor instead.
func (*GoogleAds) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{6}
}

type ViewerPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *Image                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Webview       *WebView               `protobuf:"bytes,2,opt,name=webview,proto3" json:"webview,omitempty"`
	LastPage      *LastPage              `protobuf:"bytes,3,opt,name=lastPage,proto3" json:"lastPage,omitempty"`
	GoogleAds     *GoogleAds             `protobuf:"bytes,4,opt,name=googleAds,proto3" json:"googleAds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewerPage) Reset() {
	*x = ViewerPage{}
	mi := &file_schema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewerPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewerPage) ProtoMessage() {}

func (x *ViewerPage) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewerPage.ProtoReflect.Descriptor instead.
func (*ViewerPage) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{7}
}

func (x *ViewerPage) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ViewerPage) GetWebview() *WebView {
	if x != nil {
		return x.Webview
	}
	return nil
}

func (x *ViewerPage) GetLastPage() *LastPage {
	if x != nil {
		return x.LastPage
	}
	return nil
}

func (x *ViewerPage) GetGoogleAds() *GoogleAds {
	if x != nil {
		return x.GoogleAds
	}
	return nil
}

type BookViewerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewerTitle   string                 `protobuf:"bytes,1,opt,name=viewerTitle,proto3" json:"viewerTitle,omitempty"`
	Pages         []*ViewerPage          `protobuf:"bytes,2,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookViewerResponse) Reset() {
	*x = BookViewerResponse{}
	mi := &file_schema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookViewerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookViewerResponse) ProtoMessage() {}

func (x *BookViewerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookViewerResponse.ProtoReflect.Descriptor instead.
func (*BookViewerResponse) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{8}
}

func (x *BookViewerResponse) GetViewerTitle() string {
	if x != nil {
		return x.ViewerTitle
	}
	return ""
}

func (x *BookViewerResponse) GetPages() []*ViewerPage {
	if x != nil {
		return x.Pages
	}
	return nil
}

type WebMangaViewerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *BookViewerResponse    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebMangaViewerResponse) Reset() {
	*x = WebMangaViewerResponse{}
	mi := &file_schema_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebMangaViewerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebMangaViewerResponse) ProtoMessage() {}

func (x *WebMangaViewerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebMangaViewerResponse.ProtoReflect.Descriptor instead.
func (*WebMangaViewerResponse) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{9}
}

func (x *WebMangaViewerResponse) GetData() *BookViewerResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type WebMangaViewerRequest_ChapterArgument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MangaId       uint32                 `protobuf:"varint,1,opt,name=mangaId,proto3" json:"mangaId,omitempty"`
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebMangaViewerRequest_ChapterArgument) Reset() {
	*x = WebMangaViewerRequest_ChapterArgument{}
	mi := &file_schema_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebMangaViewerRequest_ChapterArgument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebMangaViewerRequest_ChapterArgument) ProtoMessage() {}

func (x *WebMangaViewerRequest_ChapterArgument) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebMangaViewerRequest_ChapterArgument.ProtoReflect.Descriptor instead.
func (*WebMangaViewerRequest_ChapterArgument) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{2, 0}
}

func (x *WebMangaViewerRequest_ChapterArgument) GetMangaId() uint32 {
	if x != nil {
		return x.MangaId
	}
	return 0
}

func (x *WebMangaViewerRequest_ChapterArgument) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

var File_schema_proto protoreflect.FileDescriptor

const file_schema_proto_rawDesc = "" +
	"\n" +
	"\fschema.proto\"\xb2\x01\n" +
	"\n" +
	"DeviceInfo\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x16\n" +
	"\x06appVer\x18\x02 \x01(\tR\x06appVer\x12\x1e\n" +
	"\n" +
	"deviceType\x18\x03 \x01(\x05R\n" +
	"deviceType\x12\x14\n" +
	"\x05osVer\x18\x04 \x01(\tR\x05osVer\x12\x1a\n" +
	"\bisTablet\x18\x05 \x01(\bR\bisTablet\x12\"\n" +
	"\fimageQuality\x18\x06 \x01(\x05R\fimageQuality\"3\n" +
	"\tUserPoint\x12\x12\n" +
	"\x04free\x18\x01 \x01(\rR\x04free\x12\x12\n" +
	"\x04paid\x18\x02 \x01(\rR\x04paid\"\xcb\x02\n" +
	"\x15WebMangaViewerRequest\x12+\n" +
	"\n" +
	"deviceInfo\x18\x01 \x01(\v2\v.DeviceInfoR\n" +
	"deviceInfo\x12\x1c\n" +
	"\tuseTicket\x18\x02 \x01(\bR\tuseTicket\x12.\n" +
	"\fconsumePoint\x18\x03 \x01(\v2\n" +
	".UserPointR\fconsumePoint\x12\x1c\n" +
	"\tchapterId\x18\x04 \x01(\rR\tchapterId\x12P\n" +
	"\x0fchapterArgument\x18\x05 \x01(\v2&.WebMangaViewerRequest.ChapterArgumentR\x0fchapterArgument\x1aG\n" +
	"\x0fChapterArgument\x12\x18\n" +
	"\amangaId\x18\x01 \x01(\rR\amangaId\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\"\xb7\x02\n" +
	"\x05Image\x12\x1a\n" +
	"\bimageUrl\x18\x01 \x01(\tR\bimageUrl\x12\x1c\n" +
	"\turlScheme\x18\x02 \x01(\tR\turlScheme\x12\x0e\n" +
	"\x02iv\x18\x03 \x01(\tR\x02iv\x12$\n" +
	"\rencryptionKey\x18\x04 \x01(\tR\rencryptionKey\x12\x1e\n" +
	"\n" +
	"imageWidth\x18\x05 \x01(\rR\n" +
	"imageWidth\x12 \n" +
	"\vimageHeight\x18\x06 \x01(\rR\vimageHeight\x12 \n" +
	"\visExtraPage\x18\a \x01(\bR\visExtraPage\x12\x18\n" +
	"\aextraId\x18\b \x01(\rR\aextraId\x12\x1e\n" +
	"\n" +
	"extraIndex\x18\t \x01(\rR\n" +
	"extraIndex\x12 \n" +
	"\vextraSlotId\x18\n" +
	" \x01(\rR\vextraSlotId\"\x1b\n" +
	"\aWebView\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\n" +
	"\n" +
	"\bLastPage\"\v\n" +
	"\tGoogleAds\"\x9f\x01\n" +
	"\n" +
	"ViewerPage\x12\x1c\n" +
	"\x05image\x18\x01 \x01(\v2\x06.ImageR\x05image\x12\"\n" +
	"\awebview\x18\x02 \x01(\v2\b.WebViewR\awebview\x12%\n" +
	"\blastPage\x18\x03 \x01(\v2\t.LastPageR\blastPage\x12(\n" +
	"\tgoogleAds\x18\x04 \x01(\v2\n" +
	".GoogleAdsR\tgoogleAds\"Y\n" +
	"\x12BookViewerResponse\x12 \n" +
	"\vviewerTitle\x18\x01 \x01(\tR\vviewerTitle\x12!\n" +
	"\x05pages\x18\x02 \x03(\v2\v.ViewerPageR\x05pages\"A\n" +
	"\x16WebMangaViewerResponse\x12'\n" +
	"\x04data\x18\x02 \x01(\v2\x13.BookViewerResponseR\x04dataB\vZ\t./rippersb\x06proto3"

var (
	file_schema_proto_rawDescOnce sync.Once
	file_schema_proto_rawDescData []byte
)

func file_schema_proto_rawDescGZIP() []byte {
	file_schema_proto_rawDescOnce.Do(func() {
		file_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)))
	})
	return file_schema_proto_rawDescData
}

var file_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_schema_proto_goTypes = []any{
	(*DeviceInfo)(nil),                            // 0: DeviceInfo
	(*UserPoint)(nil),                             // 1: UserPoint
	(*WebMangaViewerRequest)(nil),                 // 2: WebMangaViewerRequest
	(*Image)(nil),                                 // 3: Image
	(*WebView)(nil),                               // 4: WebView
	(*LastPage)(nil),                              // 5: LastPage
	(*GoogleAds)(nil),                             // 6: GoogleAds
	(*ViewerPage)(nil),                            // 7: ViewerPage
	(*BookViewerResponse)(nil),                    // 8: BookViewerResponse
	(*WebMangaViewerResponse)(nil),                // 9: WebMangaViewerResponse
	(*WebMangaViewerRequest_ChapterArgument)(nil), // 10: WebMangaViewerRequest.ChapterArgument
}
var file_schema_proto_depIdxs = []int32{
	0,  // 0: WebMangaViewerRequest.deviceInfo:type_name -> DeviceInfo
	1,  // 1: WebMangaViewerRequest.consumePoint:type_name -> UserPoint
	10, // 2: WebMangaViewerRequest.chapterArgument:type_name -> WebMangaViewerRequest.ChapterArgument
	3,  // 3: ViewerPage.image:type_name -> Image
	4,  // 4: ViewerPage.webview:type_name -> WebView
	5,  // 5: ViewerPage.lastPage:type_name -> LastPage
	6,  // 6: ViewerPage.googleAds:type_name -> GoogleAds
	7,  // 7: BookViewerResponse.pages:type_name -> ViewerPage
	8,  // 8: WebMangaViewerResponse.data:type_name -> BookViewerResponse
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_schema_proto_init() }
func file_schema_proto_init() {
	if File_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_proto_rawDesc), len(file_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_proto_goTypes,
		DependencyIndexes: file_schema_proto_depIdxs,
		MessageInfos:      file_schema_proto_msgTypes,
	}.Build()
	File_schema_proto = out.File
	file_schema_proto_goTypes = nil
	file_schema_proto_depIdxs = nil
}
