// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultDocumentsFolder():Promise<string>;

export function Rip(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectTargetDirectory():Promise<string>;
