// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultDocumentsFolder() {
  return window['go']['main']['App']['GetDefaultDocumentsFolder']();
}

export function Rip(arg1, arg2, arg3) {
  return window['go']['main']['App']['Rip'](arg1, arg2, arg3);
}

export function SelectTargetDirectory() {
  return window['go']['main']['App']['SelectTargetDirectory']();
}
